
Comments:

To fix the error ImportError: cannot import name ‘force_text’ from ‘django.utils.encoding’ is required to perform the following replacement in /venv/lib/graphene_django/utils/utils.py 
force_text doesn't exists in django >= 4 now is force_str: https://exerror.com/importerror-cannot-import-name-force_text-from-django-utils-encoding/